---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache Webserver on Ubuntu(apache2)
    apt:
      name: apache2 
      state: present
  - name: Start Apache server
    service:
       name: apache2
       state: started
  - name: Install Tomcat on RedHat(httpd)
    yum:
      name: httpd
      state: present
  - name: Start RedHat server
    service:
       name: httpd
       state: started

    
