---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache Webserver on Ubuntu
    apt:
      name: apache2 
      state: present
  - name: Start Apache server
    service:
       name: apache2
       state: started
    
