---
# tasks file for tomcat
- name: install tomcat on RedHat
  yum:
    name: tomcat
    state: present
  when: ansible_os_family =="RedHat"

- name: copy the tomcat config file on all nodes
  template:
    src: templates/tomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  when: ansible_os_family =="RedHat"

- name: Install Admin Packages on all nodes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps  
  when: ansible_os_family =="RedHat"

- name: Configure Tomcat Web Management Interface on all nodes
  template:
    src: templates/tomwebmi.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: tomstart
  when: ansible_os_family =="RedHat"

- name: Start Tomcat
  service: 
    - name: tomcat 
      state: started 
      enabled: yes
